    spring:
      h2.console:
        enable: true
        path: '/console'
      main:
        banner-mode: off
      datasource:
        url: 'jdbc:h2:file:/C:/Users/rmecwaldowski/Documents/MyPrograms/ToDoApplication/com.pgs.todo/src/main/resources/todo-db'
      jpa:
        hibernate:
          ddl-auto: validate
    management:
      endpoints:
        web:
          exposure:
            include: '*'

    keycloak:
      auth-server-url: 'http://localhost:8180/auth'
      realm: 'ToDoApplication'
      resource: 'todo-spring-client'
      public-client: true